---
title: "Self_report_2"
author: "Matt Gehr"
date: "9/1/2021"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(readxl)
library(rstatix)
```
Loading in the data 
```{r}
data<- read_excel(path = "/Users/matthew/Documents/Documents/Professional/Graduate school/UGA/Lab stuff/Perception of videos/ssVEP/Analysis/Self_report/Perception of Videos_UGA.xlsx")
header.true <- function(df) {
 names(df) <- as.character(unlist(df[1,]))
  df[-1,]
}
data<- header.true(data)
presentation_order<- read_excel("/Users/matthew/Documents/Documents/Professional/Graduate school/UGA/Lab stuff/Perception of videos/ssVEP/Analysis/Self_report/Presentation_Order.xlsx")

par_ids<- data$`Enter the Participants ID number`
```
Getting data in order, adding video names, categories, and row means
```{r}
Flip <- function(x) 10 - x #necessary since we have higher emotions as lower numbers and that is confusing visually 

toMatch<- c("How pleasant did the previous scene make you feel?", "How aroused did the previous scene make you feel?", "How disgusted did the previous scene make you feel?", "How fearful did the previous scene make you feel?", "How much action was depicted in the scene?", "How sad did the previous scene make you feel?",  "How joyful did previous the scene make you feel?", "How angry did the previous scene make you feel?", "How surprised did the previous scene make you feel?")

dat_relevant<-data %>%
  .[, grep(paste(toMatch, collapse = "|"), names(.))] %>%
  sapply(as.numeric) %>%
  Flip() %>%
  t()%>%
  as.data.frame() 

presentation_order_long<- presentation_order %>%
  slice(rep(1:n(), each = 9))

dat_long<- data.frame()
  
for (col in 1:ncol(dat_relevant)){
  sliced_col<- dat_relevant[col]
  par_id_tobind<- rep(par_ids[col], each = length(dat_relevant$V1))
  temp1<- cbind(sliced_col, par_id_tobind, presentation_order_long)
  colnames(temp1)<- (c("Response", "Participant_ID", "Video_name", "Video_category"))
  dat_long<- rbind(dat_long, temp1)
}  
  
  

```
